# You can use this file to create a conda environment for this pipeline:
#   conda env create --name tRNAstudioEnv --file=environment.yml
name: tRNAstudioEnv
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::samtools=1.12
  - bioconda::bamread=0.0.9
  - bioconda::bowtie2=2.4.2 
  - bioconda::picard=2.25.5
  - bioconda::bedtools=2.30.0
  - bioconda::sra-tools=2.9.6
  - bioconda::pear=0.9.6
  - bioconda::subread=2.0.1
  - conda-forge::r-base=4.1.1
  - bioconda::bioconductor-glimma=2.2.0
  - bioconda::bioconductor-deseq2=1.32.0
  - bioconda::bioconductor-rsamtools=2.8.0
  - bioconda::bioconductor-GenomicAlignments=1.28.0
  - bioconda::bioconductor-genomicfeatures=1.44.0
  - bioconda::bioconductor-edgeR=3.34.0
  - bioconda::bioconductor-rsubread=2.8.0
  - bioconda::bioconductor-vsn=3.60.0
  - bioconda::bioconductor-ReportingTools=2.32.0
  - bioconda::bioconductor-seqlogo=1.60.0
  
  - conda-forge::python=3.7
  - conda-forge::r-ggseqlogo=0.1
  - conda-forge::r-ggthemes=4.2.4
  - conda-forge::r-ggtext=0.1.1
  - conda-forge::r-viridis=0.6.2
  - conda-forge::r-tidyr=1.1.4
  - conda-forge::r-stringr=1.4.0
  - conda-forge::r-gtools=3.9.2
  - conda-forge::r-gdata=2.18.0
  - conda-forge::r-dplyr=1.0.7
  - conda-forge::r-plyr=1.8.6
  - conda-forge::r-data.table=1.14.2
  - conda-forge::r-heatmaply=1.3.0
  - conda-forge::r-gridExtra=2.3
  - conda-forge::r-ggplot2=3.3.5
  - conda-forge::r-magick=2.7.3
  - conda-forge::r-xtable=1.8_4
  - conda-forge::r-knitr=1.35
  - conda-forge::r-devtools=2.4.2
  - conda-forge::r-RColorBrewer=1.1_2
  - conda-forge::r-ggrepel=0.9.1
  - conda-forge::r-readxl=1.3.1
  - conda-forge::r-tidyverse=1.3.1
  - conda-forge::r-factoextra=1.0.7
  - conda-forge::r-FactoMineR=2.4
  - conda-forge::r-htmltools=0.5.2
  - conda-forge::r-pheatmap=1.0.12
  - conda-forge::r-xlsx=0.6.5
  - conda-forge::wget=1.20.3

  - pip
  - pip:
    - pysam==0.15.4
    - pysamstats==1.1.2
    - pandas==1.3.5
    - biopython==1.79
    - tk==0.1.0
