# You can use this file to create a conda environment for this pipeline:
#   conda env create --name tRNAstudioEnv --file=environment.yml
name: tRNAstudioEnv
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::samtools=1.12
  - bioconda::bowtie2=2.4.2 
  - bioconda::picard=2.25.5
  - bioconda::bedtools=2.30.0
  - conda-forge::r-base=4.1.0
  - bioconda::bioconductor-glimma
  - bioconda::bioconductor-deseq2
  - bioconda::bioconductor-rsamtools
  - bioconda::bioconductor-GenomicAlignments
  - bioconda::bioconductor-genomicfeatures
  - bioconda::bioconductor-edgeR
  - bioconda::bioconductor-rsubread
  - bioconda::bioconductor-vsn
  - bioconda::bioconductor-ReportingTools
  - conda-forge::python=3.7
  - conda-forge::r-tidyr
  - conda-forge::r-stringr
  - conda-forge::r-gtools
  - conda-forge::r-gdata
  - conda-forge::r-dplyr
  - conda-forge::r-plyr
  - conda-forge::r-data.table
  - conda-forge::r-heatmaply
  - conda-forge::r-gridExtra
  - conda-forge::r-ggplot2
  - conda-forge::r-magick
  - conda-forge::r-xtable
  - conda-forge::r-knitr
  - conda-forge::r-devtools
  - conda-forge::r-RColorBrewer
  - conda-forge::r-ggrepel
  - conda-forge::r-readxl
  - conda-forge::r-tidyverse
  - conda-forge::r-factoextra
  - conda-forge::r-FactoMineR
  - conda-forge::r-htmltools
  - conda-forge::r-pheatmap
  - conda-forge::wget

  - pip
  - pip:
    - pysam==0.15.4
    - pysamstats==1.1.2
    - pandas
    - biopython
    - tk
